== Deploy on Heroku

Deploy a QiWeb Application on Heroku is rather simple: launching the main class with a correct classpath is enough.

Application classpath building is a good job for a build system with dependency management like Gradle or Maven.

Deploy on Heroku means building an executable version of the application and writing a `Procfile` file relaying the
Heroku environment variables to our application.
If you are not familiar with Heroku, see the https://devcenter.heroku.com/articles/java[Java] and
https://devcenter.heroku.com/articles/procfile[Procfile] documentation.

QiWeb Applications configuration properties can easily be set from the command line, you can use this mechanism in
your `Procfile`.
However, if you feel the need, nothing stops you to gather System Properties directly from your Application's code.

Now that we saw the basics we'll walk through two practical cases.
The first one using Gradle, the second one using Maven.
If you don't use any of theses to build your application, keep reading.
What's show below should apply to every situation with a few changes.

In theses two samples, we pass to the application the HTTP server listening port.
Heroku set the port to use in the `POST` environment variable.

=== Using Gradle

.`build.gradle`
["source","groovy",subs="attributes"]
----
apply plugin: 'java'

dependencies {

    compile "org.qiweb:org.qiweb.api:{qiweb_version}"
    // Add application compile dependencies

    runtime "org.qiweb:org.qiweb.server.bootstrap:{qiweb_version}"
    // Add application runtime dependencies

    test "org.qiweb:org.qiweb.test:{qiweb_version}"
    // Add application test dependencies

}

apply plugin: 'application'

mainClassName = 'org.qiweb.server.bootstrap.Main'
applicationName = 'app'

task stage( dependsOn: [ 'clean', 'installApp' ] )
----

To test locally:

[source,bash]
----
user@host $ gradle stage
# [Removed output]

BUILD SUCCESSFUL

user@host $ ./build/install/app/bin/app
----

Procfile

[source,bash]
----
web: ./build/install/app/bin/app.sh -Dqiweb.http.address=0.0.0.0 -Dqiweb.http.port=$PORT
----

=== Using Maven

NOTE: TODO Write Heroku Maven based deployment walkthrough
