== Deploy on Heroku

Deploy a QiWeb Application on Heroku is rather simple: launching the main class with a correct classpath is enough.

Application classpath building is a good job for a build system with dependency management like Gradle or Maven.

Deploy on Heroku means building an executable version of the application and writing a `Procfile` file relaying the
Heroku environment variables to our application.
If you are not familiar with Heroku, see the https://devcenter.heroku.com/articles/java[Java] and
https://devcenter.heroku.com/articles/procfile[Procfile] documentation.

QiWeb Applications configuration properties can easily be set from the command line, you can use this mechanism in
your `Procfile`.
However, if you feel the need, nothing stops you to gather System Properties directly from your Application's code.

Now that we saw the basics we'll walk through two practical cases.
The first one using Gradle, the second one using Maven.

In theses two samples, we pass the HTTP server listening port to the application.
Heroku set the port to use in the `POST` environment variable.


=== Using Gradle

Given that your application is named `app`, put the following in a file named `Procfile` at the root of your project:

[source,bash]
----
web: ./build/install/app/bin/app.sh -Dqiweb.http.address=0.0.0.0 -Dqiweb.http.port=$PORT
----

Heroku Gradle support will invoke the `stage` task provided by the `org.qiweb.application` plugin.
This task deploy the application distribution filetree in `build/install/app`.
The `Procfile` will then run your application.

You can use the `stage` task to test locally:

[source,bash]
----
user@host $ gradle stage
# [Removed output]

BUILD SUCCESSFUL

user@host $ ./build/install/app/bin/app
----


=== Using Maven

NOTE: TODO Write Heroku Maven based deployment walkthrough
