
os: linux
sudo: false

language: java
jdk: oraclejdk8

env: TERM=dumb

before_install: true
install: true
script: ./check.sh
after_failure: ./travis/after_failure.sh

notifications:
    irc: "chat.freenode.net##werval"
    use_notice: true
