
language: java

jdk:
    - oraclejdk8

env:
    - TERM=dumb

before_install: true

install:
    - ./build.sh

script:
    - ./check.sh

notifications:
    irc: "chat.freenode.net##werval"
    use_notice: true
