
language: java

jdk:
    - oraclejdk8

env:
    - TERM=dumb

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq graphviz

install: true

script:
    - ./check.sh

after_failure:
    - ./travis/after_failure.sh

notifications:
    irc: "chat.freenode.net##werval"
    use_notice: true
