
os: linux
sudo: false

env:
    - TERM=dumb

cache:
    directories:
        - ~/.gradle/caches

services:
    - memcached
    - redis-server

language: java
jdk: oraclejdk8

before_install: true
install: true
script: ./check.sh
after_failure: ./travis/after_failure.sh

notifications:
    irc: "chat.freenode.net##werval"
    use_notice: true
