
== Plugins

Werval Plugins are bound to the Application lifecycle and provide an API to the Application code.
In other words, Plugins are activated/passivated alongside the Application and they provide a facade you can use in your
controllers/filters.

TIP: To use a plugin in your Application it is enough for it to be on the classpath and declared in your configuration.

Writing a plugin is as easy as implementing `io.werval.api.Plugin`.
As an example is worth a thousand words, we'll go through the process of writing a *Hello World* Plugin.

Our `HelloWorldPlugin` will expose a `HelloWorld` API to the Application code;

[source,java]
----
public class HelloWorld
{
    public String sayHello( String name )
    {
        return String.format( "Hello %s!", name );
    }
}
----

and by so be declared that way;

[source,java]
----
public class HelloWorldPlugin implements io.werval.api.Plugin<HelloWorld>
{
    private final HelloWorld api = new HelloWorld();

    @Override
    public Class<HelloWorld> apiType()
    {
        return HelloWorld.class;
    }

    @Override
    public HelloWorld api()
    {
        return api;
    }
}
----

Now, you need to register the Plugin into your Application in its configuration:

[source,bash]
----
app.plugins.enabled += fqcn.of.HelloWorldPlugin
----

Et voilà!
Finaly, here is how to use the Plugin from your Application code:

[source,java]
----
HelloWorld helloWorld = application().plugin( HelloWorld.class );
String greeting = helloWorld.sayHello( "World" );
// Do something clever with greeting
----

To go further, the `Plugin` interface declare two lifecycle methods:

- `onActivation( Application application );`
- `onPassivation( Application application );`

Theses two are NOOP defender methods in the `Plugin` interface used above.
Override theses to hook your Plugin in the Application lifecycle.
