== Frequenty Asked Questions

:toc:

NOTE: New FAQs are appended to the bottom of this document.


=== How is "QiWeb" pronounced?

QiWeb is pronouced "chee web".


=== What the heck is this name?

QiWeb is the name of QiWeb.

Read it many times.

...

What was the question already?


=== Why choose Java as implementation language?

First, the Java programming language is widely used and well known by a lot of developpers.
It emerged in the early 90s, that is more than 20 years ago.
So it is old enough to be considered as mature.
With an eventful history, it keeps moving.

Second, the main Java running platform, a.k.a the JVM, is quite ubiquitous on the x86 architecture, supported on almost
every operating system and cloud provider.
It is now open-source and already available to ARM architectures as a
https://jdk8.java.net/download.html[JDK8 Developer Preview].

Third, Java:

- has excellent developer tooling (IDEs with automated complex refactorings, continuous integration, static code
analysis etc...) ;
- comes with a large choice of 3rd party libraries ;
- is hugely specified and documented.

And last but not least, the JVM is not tight to the Java programming language as it can run code written in
https://en.wikipedia.org/wiki/List_of_JVM_languages[over 50 languages].


=== Can I write my application code in {put.your.language.here}?

As long as it runs on the JVM, yes!

There are some guides for specific languages but the idea is pretty simple and applicable to any.
The Global object allows you take control of controllers and filters instanciation and invocation.
You just have to write some glue code.
Ah, I see your Global object is already in Groovy, cool.

Development mode should work in most situations provided your build system is set up correctly.


=== Is it possible to embedd the QiWeb Runtime?

The framework provide a default `main` class/method for you to reuse but you can also write yours if you need it.
This way of running a QiWeb Application can be seen as embedding QiWeb.

See the XXX section of the QiWeb manual to get some know-how.

