== Getting Started

As a starting point we'll see how to build a "Hello World" style example.
As QiWeb is build system agnostic we'll do this in three flavours: using the `qiweb` command line, Gradle and then
Maven.

NOTE: Even if you plan to use Gradle, Maven or any other build system, continue reading as you'll get
accustomed to the way QiWeb applications are layed out and will learn how to generate skeleton applications
quickly.

// For the code-impatients, our https://github.com/qiweb/org.qiweb.getting-started[getting-started repository] contains
// the code presented in theses sections.

After that we'll take a look at the QiWeb development shell features.
We hope you'll find your way through.

CAUTION: Maven Plugins cannot be built with Java 8 yet so the QiWeb Maven Plugin is not published, yet!

include::src/asciidoc/getting-started/hello-cli.adoc[]
include::src/asciidoc/getting-started/hello-gradle.adoc[]
include::src/asciidoc/getting-started/hello-maven.adoc[]
include::src/asciidoc/getting-started/using-devshell.adoc[]

=== Next steps

Now that you have a minimal skeleton, the obvious next step is to write your application.

You can use the following resources to learn what you need:

- link:samples.html[Sample applications], ready to run, with documentation and tests
- link:manual.html[Manual]
- link:api/index.html[API Docs]
- link:libraries.html[Libraries]
- link:guides.html[Guides]
