
== Gradle Plugin

.`./build.gradle`
["source","groovy",subs="attributes,callouts"]
----
buildscript {
  repositories { maven { url 'https://repo.codeartisans.org/qiweb' } }    // <1>
  dependencies { classpath 'org.qiweb:org.qiweb.gradle:{werval_version}' } // <2>
}

apply plugin: 'org.qiweb.application'       // <3>
----
<1> Declare Werval repository for the build
<2> Add Werval Gradle Plugin to build classpath
<3> Apply the Werval Gradle plugin


=== Werval dependencies

Use Werval dependencies of the same version as the Werval Gradle plugin:

[source]
----
dependencies {
  compile qiweb.api
  compile qiweb.module('json')
  runtime qiweb.nettyServer
  testCompile qiweb.test
}
----



=== Application packaging

`gradle distZip`

TIP: If you need RPM or DEB packaging, use the
https://github.com/nebula-plugins/gradle-ospackage-plugin[gradle-ospackage-plugin].



=== Staging for production

`gradle stage`



=== Development mode


[discrete]
==== Build logic

The Werval Gradle plugin:

- declare a `devshell` task that depend on the `classes` task.
- declare a `devshell_rebuild` task that depend on the `classes` task too.

When running the `devshell` task it will run `classes` and other dependents tasks and then the Werval DevShell, embedded.
The application is now running in development mode.

Once a source code change is detected, the first request received by the application summon a gradle daemon to run
the `devshell_rebuild` task on the application project.

You add dependent tasks to the `devshell` and `devshell_rebuild` that way;

[source]
----
devshell.dependsOn gulp_bower, gulp_dev
devshell_rebuild.dependsOn gulp_dev
----

This example is from an application that use `bower` and `gulp` for client javascript build,
thanks to the `gradle-gulp-plugin`.

Configuring theses tasks in your build allow you to fine tune the work needed to get your app in dev mode and what
should be done when the source has changed.


[discrete]
==== Watch extra files or directories

The `devshell` task has an `extraWatch` property that allow one to add files or directories to watch for changes in
dev mode:

[source]
----
devshell.extraWatch += "path/to/dir"
devshell.extraWatch += [ "path/to/elsewhere", "and/anywhere" ]
----

Thanks to Gradle's incredible incremental build behaviour, handling complex build scenarios is both confy and
productive.


[discrete]
==== Development only dependencies

You can enrich the application classpath in development mode by adding dependencies to the `devshell` configuration:

[source]
----
dependencies {
  devshell 'group:id:version'
}
----


[discrete]
==== Development only sources

You can also enrich the application classpath in development mode by adding files to the `dev`
http://www.gradle.org/docs/current/userguide/java_plugin.html[source-set],
that is in `src/dev/java` and `src/dev/resources`.

Typical usage is to use development specific configuration.
Putting it in the `dev` source-set prevent it to be in the application distribution.

This is achieved in two steps,

- add a `developement.conf` file in `src/dev/resources` with at least `include "application.conf"` in it ;
- use `development.conf` as application configuration in development mode:

[source]
----
devshell.configResource 'development.conf'
----

You can now add content to `development.conf` to define configuration properties that will be used in development mode
only.



=== Override config location

["source","groovy"]
----
devshell {
  // Only one of theses three can be set
  configResource = "application-dev.conf"
  configFile = file( "path/to/file.conf" )
  configUrl = new URL( "http://url.to/file.conf" )
}

start {
  // Only one of theses three can be set
  configResource = "application-dev.conf"
  configFile = file( "path/to/file.conf" )
  configUrl = new URL( "http://url.to/file.conf" )
}

// Sample custom start task
task customStart( type: org.qiweb.gradle.StartTask )
{
  configResource = "application-custom.conf"
}
----
