
=== Hello Maven QiWeb

> Build managed

In this short tutorial we'll enhance an application generated by the `qiweb` command line using Maven.

IMPORTANT: You need to install http://maven.apache.org[Maven] to be able to complete this tutorial.

Rename the `pom.xml.example` file at the application root to `pom.xml`.

Here is what you'll find inside:

// TODO XML is not correctly rendered if ["source","xml",subs="attributes"] is used ... FIXME!
.`./pom.xml`
[source,xml]
----
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>hello-qiweb</groupId>
    <artifactId>hello-qiweb</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <repositories>
        <repository>
            <id>qiwebRepo</id>
            <url>https://repo.codeartisans.org/qiweb</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.qiweb</groupId>
            <artifactId>org.qiweb.api</artifactId>
            <version>{qiweb-version}</version>
        </dependency>
        <dependency>
            <groupId>org.qiweb</groupId>
            <artifactId>org.qiweb.server.bootstrap</artifactId>
            <version>{qiweb-version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.qiweb</groupId>
            <artifactId>org.qiweb.test</artifactId>
            <version>{qiweb-version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <pluginRepositories>
        <pluginRepository>
            <id>qiwebRepo</id>
            <url>https://repo.codeartisans.org/qiweb</url>
        </pluginRepository>
    </pluginRepositories>
    
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.qiweb</groupId>
                <artifactId>org.qiweb.maven</artifactId>
                <version>{qiweb-version}</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>appassembler-maven-plugin</artifactId>
                <version>1.8</version>
                <executions>
                    <execution>
                        <id>app-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>assemble</goal>
                        </goals>
                        <configuration>
                            <repositoryLayout>flat</repositoryLayout>
                            <repositoryName>lib</repositoryName>
                            <programs>
                                <program>
                                    <id>${project.artifactId}</id>
                                    <mainClass>org.qiweb.server.bootstrap.Main</mainClass>
                                </program>
                            </programs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
----

And that's it!
You can now use Maven to compile, develop, test, assemble and run your application.

CAUTION: If you did'nt use the `qiweb` command line to generate an application skeleton you miss an application secret.
You can generate a new one by typing `mvn qiweb:secret` on the command line.
Don't forget to add it to your `application.conf` file with the `app.secret` key.

.Run in development mode
[source]
----
user@host ~/hello-qiweb $ mvn qiweb:devshell
----

.Run tests
[source]
----
user@host ~/hello-qiweb $ mvn test
----

.Run in production mode
[source]
----
user@host ~/hello-qiweb $ mvn qiweb:start
----

.Generate distribution
[source]
----
user@host ~/hello-qiweb $ mvn package
----


TIP: If you need RPM or DEB packaging, use the http://mojo.codehaus.org/rpm-maven-plugin[rpm-maven-plugin] and https://github.com/tcurdt/jdeb[jdeb-maven-plugin]


