
=== Hello Maven QiWeb

> Build managed

In this short tutorial we'll enhance an application generated by the `qiweb` command line using Maven.

IMPORTANT: You need to install http://maven.apache.org[Maven] to be able to complete this tutorial.

Create a `pom.xml` file at the application root with the following content:

// TODO XML is not correctly rendered if ["source","xml",subs="attributes"] is used ... FIXME!
.`./pom.xml`
[source,xml]
----
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>hello-qiweb</groupId>
    <artifactId>hello-qiweb</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        
        <dependency>
            <groupId>org.qiweb</groupId>
            <artifactId>org.qiweb.api</artifactId>
            <version>{qiweb-version}</version>
        </dependency>
        
        <!-- Runtime -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.0.11</version>
            <scope>runtime</scope>
        </dependency>
        
        <!-- Tests -->
        <dependency>
            <groupId>org.qiweb</groupId>
            <artifactId>org.qiweb.test</artifactId>
            <version>{qiweb-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit-dep</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>

    </dependencies>
    
    <properties>
        <mainClassName>org.qiweb.server.bootstrap.Main</mainClassName>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.qiweb</groupId>
                <artifactId>org.qiweb.maven</artifactId>
                <version>{qiweb-version}</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.2.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>${mainClassName}</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>appassembler-maven-plugin</artifactId>
                <version>1.3.1</version>
                <configuration>
                    <repositoryLayout>flat</repositoryLayout>
                    <repositoryName>lib</repositoryName>
                    <programs>
                        <program>
                            <name>${project.artifactId}</name>
                            <mainClass>${mainClassName}</mainClass>
                        </program>
                    </programs>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
----

And that's it!
You can now use Maven to compile, develop, test, assemble and run your application.

CAUTION: If you did'nt use the `qiweb` command line to generate an application skeleton you miss an application secret.
You can generate a new one by typing `mvn qiweb:secret` on the command line.
Don't forget to add it to your `application.conf` file with the `app.secret` key.

.Run in development mode
[source]
----
user@host ~/hello-qiweb $ mvn qiweb:devshell
----

.Run tests
[source]
----
user@host ~/hello-qiweb $ mvn test
----

.Run in production mode
[source]
----
user@host ~/hello-qiweb $ mvn exec:java
----

.Generate ZIP distribution
[source]
----
user@host ~/hello-qiweb $ mvn package
----


TIP: If you need RPM or DEB packaging, use the http://mojo.codehaus.org/rpm-maven-plugin[rpm-maven-plugin] and https://github.com/tcurdt/jdeb[jdeb-maven-plugin]


