
=== Hello Gradle QiWeb

> Automation evolved

In this short tutorial we'll enhance an application generated by `qiweb-cli` using Gradle.

IMPORTANT: You need to install http://gradle.org[Gradle] to be able to complete this tutorial.

Create a `build.gradle` file at the application root with the following content:

.`./build.gradle`
["source","groovy",subs="attributes"]
----
apply plugin: 'java' // <1>

repositories {
    // mavenLocal();   // <2>
    mavenCentral(); // <3>
}

dependencies {

    compile "org.qiweb:org.qiweb.api:{qiweb-version}" // <4>
    compile "org.qiweb:org.qiweb.lib:{qiweb-version}" // <5>
    // Add application compile dependencies

    runtime "org.qiweb:org.qiweb.runtime:{qiweb-version}" // <6>
    // Add application runtime dependencies

    testCompile "org.qiweb:org.qiweb.test:{qiweb-version}" // <7>
    // Add application test dependencies

}

apply plugin: 'qiweb'

apply plugin: 'application' // <8>

mainClassName = 'org.qiweb.runtime.Main'    // <9>
applicationName = 'hello-qiweb'             // <10>
----
<1> Make this project a Java project
<2> Declare Maven local repository (only if you build QiWeb from sources)
<3> Declare Maven central repository
<4> Add compile scope dependency to QiWeb API
<5> Add compile scope dependency to QiWeb Standard Library
<6> Add runtime scope dependency to QiWeb Runtime
<7> Add test scope dependency to QiWeb Test Support
<8> Apply the Gradle http://gradle.org/docs/current/userguide/application_plugin.html[Application Plugin]
<9> Set the main class to `org.qiweb.runtime.Main` for production mode
<10> Name the archive and startup scripts

And that's it!
You can now use Gradle to compile, develop, test, assemble and run your application.

CAUTION: If you did'nt use `qiweb-cli` to generate an application skeleton you miss an application secret.
You can generate a new one by typing `gradle -q secret` on the command line.
Don't forget to add it to your `application.conf` file with the `app.secret` key.

.Run in development mode
[source]
----
user@host ~/hello-qiweb $ gradle devshell
----

.Run tests
[source]
----
user@host ~/hello-qiweb $ gradle check
----

.Run in production mode
[source]
----
user@host ~/hello-qiweb $ gradle run
----

.Generate ZIP distribution
[source]
----
user@host ~/hello-qiweb $ gradle distZip
----

