
=== Hello Gradle QiWeb

> Automation evolved

In this short tutorial we'll enhance an application generated by `qiweb-cli` using Gradle.

IMPORTANT: You need to install http://gradle.org[Gradle] to be able to complete this tutorial.

Create a `build.gradle` file at the application root with the following content:

.`./build.gradle`
["source","groovy",subs="attributes"]
----
apply plugin: 'java' // <1>

repositories {
    mavenLocal();
    mavenCentral();
    maven {
        url "http://repo.gradle.org/gradle/libs-releases-local/"
    }
}

dependencies {

    compile "org.qiweb:org.qiweb.api:{qiweb-version}" // <2>
    compile "org.qiweb:org.qiweb.lib:{qiweb-version}" // <3>
    // Add application compile dependencies

    runtime "org.qiweb:org.qiweb.runtime:{qiweb-version}" // <4>
    // Add application runtime dependencies

    testCompile "org.qiweb:org.qiweb.test:{qiweb-version}" // <5>
    // Add application test dependencies

}

apply plugin: 'qiweb'

apply plugin: 'application' // <6>

mainClassName = 'org.qiweb.runtime.Main' // <7>
applicationName = 'hello-qiweb' // <8>
----
<1> Make this project a Java project
<2> Add compile scope dependency to QiWeb API
<3> Add compile scope dependency to QiWeb Standard Library
<4> Add runtime scope dependency to QiWeb Runtime
<5> Add test scope dependency to QiWeb Test Support
<6> Apply the Gradle http://gradle.org/docs/current/userguide/application_plugin.html[Application Plugin]
<7> Set the main class to `org.qiweb.runtime.Main` for production mode
<8> Name the archive and startup scripts

And that's it!
You can now use Gradle to compile, develop, test, assemble and run your application.

TIP: If you did'nt use `qiweb-cli` to generate an application skeleton you miss an application secret.
You can generate a new one by typing `gradle -q secret` on the command line.

.Run in development mode
[source]
----
user@host ~/hello-qiweb $ gradle devshell
----

.Run tests
[source]
----
user@host ~/hello-qiweb $ gradle check
----

.Run in production mode
[source]
----
user@host ~/hello-qiweb $ gradle run
----

.Generate ZIP distribution
[source]
----
user@host ~/hello-qiweb $ gradle distZip
----

