
== Application

A QiWeb Application is nothing but a plain old Java program.
The framework provide a default `main` class/method for you to reuse but you can also write yours if you need it.

In development and test modes, no configuration file is required.
To run in production mode, the minimal requirement is a configuration file named `application.conf` containing an `app.secret` entry.


=== Structure

// TODO Application Structure Diagram - Code PoV


=== Modes

A QiWeb Application can run in three different modes:

. **Development**: the HTTP stack is single-threaded, source code is watched for changes, Application is restarted
on-demand and stacktraces are disclosed in responses.
. **Test**: the HTTP stack is single-threaded and Application run from compiled bytecode.
. **Production**: the HTTP stack is multi-threaded and Application run from compiled bytecode.


=== Runtime Models

A QiWeb Application can run according to three different runtime models:

. **Heavyweight**, with HTTP Service, most used runtime model for a HTTP application.
. **Middleweight**, with HTTP Context but without HTTP Service, typical runtime model for controller tests.
. **Lightweight**, with **no** HTTP support, useful for applying the worker runtime model easily ; that is execute some
application code in a lightweight process.

TIP: See the Deploy on Heroku guide for lightweight mode usage example implementing Heroku workers.


=== Threading Model

QiWeb has a quite simple threading model based on the Netty one.

- Netty
    - Netty Selector Threads, default to `Runtime.availableProcessors()`
     -Netty IO Threads, default to `Runtime.availableProcessors()`
- Application
    - Application Execution Thread Pool
    - It means that by default, none of your controller code is executed on the IO Threads and that any controller doing
      blocking operations will not slow your application down.


=== Summary

[cols="2a,4a,4a,4a"]
|===
||Development Mode |Test Mode |Production Mode

|**Heavyweight Runtime**
|Typical use while coding

- Single-thread HTTP stack `1 * acceptor-thread` + `1 * io-thread`
- Reload on source changes
- Stacktraces disclosed in responses
|For tests that require a complete HTTP stack

- Single-thread HTTP stack `1 * acceptor-thread` + `1 * io-thread`
- Compiled bytecode execution
|Typical production model

- Multi-thread HTTP stack `cores * acceptor-threads` + `cores * io-threads`
- Compiled bytecode execution

|**Middleweight Runtime**
|`404 No use case found`
|For QiWeb integrations tests that do not require a complete HTTP stack

- No true HTTP stack
- Compiled bytecode execution
|For **hackish** worker process that require an HTTP context but no HTTP stack

- No true HTTP stack
- Compiled bytecode execution

|**Lightweight Runtime**
|`404 No use case found`
|Typical use case for QiWeb integrations tests that need no HTTP support

- No HTTP support
- Compiled bytecode execution
|Typical worker process model

- No HTTP support
- Compiled bytecode execution

|===

