
== Testing

The `org.qiweb.test` module provide http://junit.org[JUnit] based construct to ease tests implementation.

First construct is `QiWebTest` that should be subclassed by your test classes.
Second one is `QiWebRule`, a JUnit Rule to be declared in your test classes.
Both have the same extension points, choose the one that suits your needs and habits.

Using the JUnit Rule is the prefered way of writing QiWeb tests as it don't force you to extend from any base class.

TIP: QiWeb JUnit Support has transparent integration with https://code.google.com/p/rest-assured/[rest-assured] if it is
detected on the tests classpath.
rest-assured base URL is automatically set accordingly to the QiWeb configuration so can use relative paths when using
it.

=== QiWebTest usage

[source,java]
----
import org.junit.Test;
import org.qiweb.test.QiWebTest;

public class MyTest extends QiWebTest {
  @Test
  public void myTest() {
    // Assert what you have to here
  }
}
----

Your Application will be activated/passivated around each test method.


=== QiWebRule usage

[source,java]
----
import org.junit.Rule;
import org.junit.Test;
import org.qiweb.test.QiWebTest;

public class MyTest {
  @Rule public QiWebRule qiweb = new QiWebRule();
  @Test
  public void myTest() {
    // Assert what you have to here
  }
}
----

As expected, this will activate/passivate your Application around each test method.

If you prefer to have your Application activated/passivated around each test class, use the JUnit `@ClassRule`
annotation.

[source,java]
----
import org.junit.ClassRule;
import org.junit.Test;
import org.qiweb.test.QiWebTest;

public class MyTest {
  @ClassRule public static final QiWebRule QIWEB = new QiWebRule();
  @Test
  public void myTest() {
    // Assert what you have to here
  }
}
----


=== In practice

- HTTP or not HTTP
- Automatic free port usage, allowing tests to be run in parallel
- Per Method / Per Class
- Logging
- Configuration
- Routes


=== Testing HTTP

The QiWeb Team recommend https://code.google.com/p/rest-assured/[rest-assured].
All HTTP assertions in the SDK are done using `rest-assured`, see the tests source code for numerous examples.


=== Testing browser based UIs

The QiWeb Team recommand http://fluentlenium.org/[FluentLenium].
All browser based UI assertions in the samples are done using `FluentLenium`, see the tests source code for numerous
examples.
