
== Testing

The `io.werval.test` module provide http://junit.org[JUnit] based construct to ease tests implementation.

First construct is `Werval[Http]Test` that should be subclassed by your test classes.
Second one is `Werval[Http]Rule`, a JUnit Rule to be declared in your test classes.
Both have the same extension points, choose the one that suits your needs and habits.

Using the JUnit Rules is the prefered way of writing Werval tests as they don't force you to extend from any base class.

=== Werval[Http]Test usage

[source,java]
----
import org.junit.Test;
import io.werval.test.Werval[Http]Test;

public class MyTest extends Werval[Http]Test {
  @Test
  public void myTest() {
    // Assert what you have to here
  }
}
----

Your Application will be activated/passivated around each test method.


=== WervalRule usage

[source,java]
----
import org.junit.Rule;
import org.junit.Test;
import io.werval.test.Werval[Http]Test;

public class MyTest {
  @Rule public Werval[Http]Rule qiweb = new Werval[Http]Rule();
  @Test
  public void myTest() {
    // Assert what you have to here
  }
}
----

As expected, this will activate/passivate your Application around each test method.

If you prefer to have your Application activated/passivated around each test class, use the JUnit `@ClassRule`
annotation.

[source,java]
----
import org.junit.ClassRule;
import org.junit.Test;
import io.werval.test.Werval[Http]Test;

public class MyTest {
  @ClassRule public static final Werval[Http]Rule QIWEB = new Werval[Http]Rule();
  @Test
  public void myTest() {
    // Assert what you have to here
  }
}
----


=== In practice

- HTTP or not HTTP
// - Automatic free port usage, allowing tests to be run in parallel ; even while a development shell is running
- Lifecycle around test methods, classes or suites
- Logging (Slf4jRule, Logback)
- Configuration (choose config file)
- Routes (inline or choose config file)


=== Testing HTTP

[TIP]
====
The Werval Team recommend https://code.google.com/p/rest-assured/[rest-assured].

Werval JUnit Support has transparent integration with https://code.google.com/p/rest-assured/[rest-assured] if it is
detected on the tests classpath.
rest-assured base URL is then set accordingly to the Werval configuration so you can use relative paths when using
it.

All HTTP assertions in the SDK are done using `rest-assured`, see the tests source code for numerous examples.
====


=== Testing browser based UIs

[TIP]
====
The Werval Team recommend http://fluentlenium.org/[FluentLenium].

All browser based UI assertions in the samples are done using `FluentLenium`, see the tests source code for numerous
examples.
====