
== Hello Gradle QiWeb

> Automation evolved

In this short tutorial we'll enhance an application generated by the `qiweb` command line using Gradle.

IMPORTANT: You need to install http://gradle.org[Gradle] to be able to complete this tutorial.

Rename the `build.gradle.example` file at the application root to `build.gradle`.

Here is what you'll find inside:

.`./build.gradle`
["source","groovy",subs="attributes,callouts"]
----
buildscript {	
	repositories {
    	maven {
    		url "https://repo.codeartisans.org/qiweb"
    		credentials { username = "qiweb"; password = "qiweb" } // <1>
		}
	}
	dependencies { classpath 'org.qiweb:org.qiweb.gradle:{qiweb_version}' }      // <2>
}
repositories {
    maven {
    	url "https://repo.codeartisans.org/qiweb"
    	credentials { username = "qiweb"; password = "qiweb" }     // <3>
	}
}

apply plugin: 'java'        // <4>
apply plugin: 'qiweb'       // <5>
apply plugin: 'application' // <6>

mainClassName = 'org.qiweb.server.bootstrap.Main' // <7>
applicationName = 'hello-qiweb'                   // <8>

dependencies {

    compile "org.qiweb:org.qiweb.api:{qiweb_version}" // <9>
    // Add application compile dependencies here

    runtime "org.qiweb:org.qiweb.server.bootstrap:{qiweb_version}" // <10>
    // Add application runtime dependencies here

    testCompile "org.qiweb:org.qiweb.test:{qiweb_version}" // <11>
    // Add application test dependencies here

}

----
<1> Declare QiWeb repository for the build
<2> Add QiWeb Gradle Plugin to build classpath
<3> Declare QiWeb repository for the application
<4> Apply the Gradle http://www.gradle.org/docs/current/userguide/java_plugin.html[Java Plugin]
<5> Apply the QiWeb Gradle plugin
<6> Apply the Gradle http://gradle.org/docs/current/userguide/application_plugin.html[Application Plugin] that provide scripts and packaging
<7> Set the application main class to `org.qiweb.server.bootstrap.Main` for production mode
<8> Name the application archive and startup scripts
<9> Add compile scope dependency to QiWeb API
<10> Add runtime scope dependency to QiWeb Netty Server Bootstrap
<11> Add test scope dependency to QiWeb Test Support


And that's it!
You can now use Gradle to compile, develop, test, assemble and run your application.

CAUTION: If you did'nt use the `qiweb` command line to generate an application skeleton you miss an application secret.
You can generate a new one by typing `gradle -q secret` on the command line.
Don't forget to add it to your `application.conf` file with the `app.secret` key.

.Run in development mode
[source]
----
user@host ~/hello-qiweb $ gradle devshell
----

.Run tests
[source]
----
user@host ~/hello-qiweb $ gradle check
----

.Run in production mode
[source]
----
user@host ~/hello-qiweb $ gradle start
----

.Generate ZIP distribution
[source]
----
user@host ~/hello-qiweb $ gradle distZip
----

TIP: If you need RPM or DEB packaging, use the https://github.com/nebula-plugins/gradle-ospackage-plugin[gradle-ospackage-plugin]


=== Development mode build logic


The QiWeb Gradle plugin:

- declare a `devshell` task that depend on the `classes` task.
- declare a `devshell_rebuild` task that depend on the `classes` task too.

When running the `devshell` task it will run `classes` and other dependents tasks and then the QiWeb DevShell, embedded.
The application is now running in development mode.

Once a source code change is detected, the first request received by the application summon a gradle daemon to run
the `devshell_rebuild` task on the application project.

You add dependent tasks to the `devshell` and `devshell_rebuild` that way;

[source]
----
devshell.dependsOn grunt_bower, grunt_dev
devshell_rebuild.dependsOn grunt_dev
----

This example is from an application that use `bower` and `grunt` for client javascript build,
thanks to the `gradle-grunt-plugin`.

Configuring theses tasks in your build allow you to fine tune the work needed to get your app in dev mode and what
should be done when the source has changed.

Moreover, the `devshell` task has an `extraWatch` property that allow one to add directories to watch for changes in
dev mode:

[source]
----
devshell.extraWatch += "path/to/dir"
devshell.extraWatch += [ "path/to/elsewhere", "and/anywhere" ]
----

Thanks to Gradle's incredible incremental build behaviour, handling complex build scenarios is both confy and
productive.
